### ISSUE TITLE
Error while bootstraping..

### ISSUE THREAD

**Issue by rajksbth** [cloudify-cosmo/cloudify-manager#947]
When bootstrapping using simple-manager-blueprint-inputs.yaml its thrwing error
`Uploading resources from /tmp/tmpE221EG/types.yaml to /opt/manager/resources/spec/cloudify/4.1.1
[192.168.85.157] run: sudo mkdir -p /opt/manager/resources/spec/cloudify/4.1.1
[192.168.85.157] put: /tmp/tmpE221EG/types.yaml -> /opt/manager/resources/spec/cloudify/4.1.1/types.yaml
2017-09-08 16:09:04.246  CFY <manager> Starting 'execute_operation' workflow execution
2017-09-08 16:09:04.248  CFY <manager> [sanity_i1s11e] Starting operation cloudify.interfaces.lifecycle.start (Operation parameters: {'manager_ip': u'192.168.85.157', 'run_sanity': 'true', 'fabric_env': {'port': 22, 'key_filename': u'/root/.ssh/id_rsa.pub', 'host_string': u'192.168.85.157', 'user': u'root'}})
2017-09-08 16:09:04.349  CFY <manager> [sanity_i1s11e.start] Sending task 'fabric_plugin.tasks.run_script'
2017-09-08 16:09:04.364  CFY <manager> [sanity_i1s11e.start] Task started 'fabric_plugin.tasks.run_script'
[192.168.85.157] out: /tmp2017-09-08 16:09:06.590  LOG <manager> [sanity_i1s11e.start] INFO: Starting Manager sanity check...
2017-09-08 16:09:17.907  LOG <manager> [sanity_i1s11e.start] ERROR: Failed to PUT http://192.168.85.157:80/api/v3/blueprints/sanity_bp?application_file_name=no-monitoring-singlehost-blueprint.yaml (reason: SERVICE UNAVAILABLE)
2017-09-08 16:09:23.684  LOG <manager> [sanity_i1s11e.start] ERROR: Failed to PUT http://192.168.85.157:80/api/v3/deployments/sanity_deployment (reason: SERVICE UNAVAILABLE)
2017-09-08 16:09:24.277  LOG <manager> [sanity_i1s11e.start] ERROR: Failed to GET http://192.168.85.157:80/api/v3/executions?deployment_id=sanity_deployment (reason: SERVICE UNAVAILABLE)
[192.168.85.157] out: Traceback (most recent call last):
[192.168.85.157] out:   File "/tmp/cloudify-ctx/scripts/tmpPI29AB-start.py-SU7E0TWY", line 303, in <module>
[192.168.85.157] out:     perform_sanity()
[192.168.85.157] out:   File "/tmp/cloudify-ctx/scripts/tmpPI29AB-start.py-SU7E0TWY", line 285, in perform_sanity
[192.168.85.157] out:     _prepare_sanity_app()
[192.168.85.157] out:   File "/tmp/cloudify-ctx/scripts/tmpPI29AB-start.py-SU7E0TWY", line 40, in _prepare_sanity_app
[192.168.85.157] out:     _deploy_app()
[192.168.85.157] out:   File "/tmp/cloudify-ctx/scripts/tmpPI29AB-start.py-SU7E0TWY", line 92, in _deploy_app
[192.168.85.157] out:     'deployment {0} to be created'.format(DEPLOYMENT_ID))
[192.168.85.157] out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 1118, in repetitive
[192.168.85.157] out:     if condition_func(*args, **kwargs):
[192.168.85.157] out:   File "/tmp/cloudify-ctx/scripts/utils.py", line 1562, in wait_for_workflow
[192.168.85.157] out:     res_content = res.readlines()
[192.168.85.157] out: AttributeError: 'NoneType' object has no attribute 'readlines'
[192.168.85.157] out: 
`

**Comment by mcouthon** [comment]
@rajksbth Can you please try again? The sanity mechanism has been reworked recently.
